spring.application.name=LEGACY_LENS

# =============== PORT NUMBER ===============
server.port=8086

# =============== MYSQL PROPERTIES ===============
spring.datasource.url=jdbc:mysql://localhost:3306/legacylens?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Mustafa52!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============== JPA/HIBERNATE PROPERTIES ===============
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============== JWT PROPERTIES ===============
jwt.secret=a21T1OFR2v23WfLsjnRFqdNkJDy4ER2DGw68klKW27TDMdaSn0HSmEPL1clWoM9O
jwt.expiration=10800000
jwt.reset.secret=HXkphPTCPrlgOwmKzUVgT4ekhYiNkSfZrGDWmpe1yxi0PFkuanip3n49CcC3tzerr3jIIy38RMIQdohVFw84ID
jwt.reset.expiration=900000

# =============== MAIL PROPERTIES (Gmail SMTP) ===============
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mustafa52bhagat@gmail.com
spring.mail.password=csbc jyox bblp dbgt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# =============== OTP SETTINGS ===============
app.otp.expiry-minutes=5

# =============== APP META ===============
app.name=LegacyLens



